# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1odv1avU-jMJMX1WB4hrM6CHfyJD7pRCO
"""

class Huesped:
    def __init__(self, cedula, nombre, num_habitacion):
        self.cedula = cedula
        self.nombre = nombre
        self.num_habitacion = num_habitacion

class Hotel:
    def __init__(self, num_habitaciones):
        self.num_habitaciones = num_habitaciones
        self.habitaciones_disponibles = list(range(1, num_habitaciones + 1))
        self.registro_entradas = []
        self.registro_salidas = []

    def registrar_entrada(self, cedula, nombre, num_habitacion):
        if num_habitacion in self.habitaciones_disponibles:
            huesped = Huesped(cedula, nombre, num_habitacion)
            self.registro_entradas.append(huesped)
            self.habitaciones_disponibles.remove(num_habitacion)
            print("Entrada registrada exitosamente.")
        else:
            print("La habitación está ocupada.")

    def registrar_salida(self, num_habitacion):
        huesped = None
        for h in self.registro_entradas:
            if h.num_habitacion == num_habitacion:
                huesped = h
                break

        if huesped:
            self.registro_salidas.append(huesped)
            self.registro_entradas.remove(huesped)
            self.habitaciones_disponibles.append(num_habitacion)
            print("Salida registrada exitosamente.")
        else:
            print("No se encontró ningún huésped en esa habitación.")

    def consultar_huesped_individual(self, cedula):
        for h in self.registro_entradas:
            if h.cedula == cedula:
                return h

        return None

    def consultar_huesped_total_por_cedula(self, cedula):
        huespedes = []
        for h in self.registro_entradas:
            if h.cedula == cedula:
                huespedes.append(h)

        return huespedes

    def consultar_huesped_total_por_orden_llegada(self):
        return self.registro_entradas

    def consultar_habitaciones_disponibles(self):
        return self.habitaciones_disponibles

    def consultar_habitaciones_ocupadas(self):
        habitaciones_ocupadas = list(set(range(1, self.num_habitaciones + 1)) - set(self.habitaciones_disponibles))
        return habitaciones_ocupadas
    
def mostrar_menu():
    print("===== MENÚ =====")
    print("1. Registrar entrada de un huésped")
    print("2. Registrar salida de un huésped")
    print("3. Consultar información de un huésped individual")
    print("4. Consultar información de todos los huéspedes (por cédula)")
    print("5. Consultar información de todos los huéspedes (por orden de llegada)")
    print("6. Consultar habitaciones disponibles")
    print("7. Consultar habitaciones ocupadas")
    print("8. Salir")

hotel = Hotel(10)

while True:
    mostrar_menu()
    opcion = input("Ingrese una opción: ")

    if opcion == "1":
        cedula = input("Ingrese el número de cédula: ")
        nombre = input("Ingrese el nombre del huésped: ")
        num_habitacion = int(input("Ingrese el número de habitación: "))
        hotel.registrar_entrada(cedula, nombre, num_habitacion)
        print()

    elif opcion == "2":
        num_habitacion = int(input("Ingrese el número de habitación: "))
        hotel.registrar_salida(num_habitacion)
        print()

    elif opcion == "3":
        cedula = input("Ingrese el número de cédula del huésped: ")
        huesped = hotel.consultar_huesped_individual(cedula)
        if huesped:
            print("Información del huésped:")
            print("Cédula:", huesped.cedula)
            print("Nombre:", huesped.nombre)
            print("Número de habitación:", huesped.num_habitacion)
        else:
            print("No se encontró ningún huésped con esa cédula.")
        print()

    elif opcion == "4":
        cedula = input("Ingrese el número de cédula del huésped: ")
        huespedes = hotel.consultar_huesped_total_por_cedula(cedula)
        if huespedes:
            print("Información de los huéspedes con la cédula", cedula + ":")
            for huesped in huespedes:
                print("Cédula:", huesped.cedula)
                print("Nombre:", huesped.nombre)
                print("Número de habitación:", huesped.num_habitacion)
                print()
        else:
            print("No se encontró ningún huésped con esa cédula.")
        print()

    elif opcion == "5":
        huespedes = hotel.consultar_huesped_total_por_orden_llegada()
        if huespedes:
            print("Información de todos los huéspedes (orden de llegada):")
            for huesped in huespedes:
                print("Cédula:", huesped.cedula)
                print("Nombre:", huesped.nombre)
                print("Número de habitación:", huesped.num_habitacion)
                print()
        else:
            print("No hay huéspedes registrados.")
        print()

    elif opcion == "6":
        habitaciones_disponibles = hotel.consultar_habitaciones_disponibles()
        print("Habitaciones disponibles:", habitaciones_disponibles)
        print()

    elif opcion == "7":
        habitaciones_ocupadas = hotel.consultar_habitaciones_ocupadas()
        print("Habitaciones ocupadas:", habitaciones_ocupadas)
        print()

    elif opcion == "8":
        print("Saliendo del programa...")
        break

    else:
        print("Opción inválida. Por favor, ingrese una opción válida.")
        print()